DROP DATABASE IF EXISTS palaso;
CREATE DATABASE IF NOT EXISTS palaso;

USE palaso;

CREATE TABLE LOGIN(
	log_id INT NOT NULL auto_increment,
	log_log VARCHAR(25) NOT NULL,
	log_pwd VARCHAR(8) NOT NULL,
	CONSTRAINT PK_LOGIN PRIMARY KEY (log_id)
)Engine=InnoDB;

CREATE TABLE CIVILITES(
	civ_id INT NOT NULL auto_increment,
	civ_code VARCHAR(4) NOT NULL, 
	civ_libelle VARCHAR(45) NOT NULL, 
	CONSTRAINT PK_CIV PRIMARY KEY (civ_id) 
)Engine=InnoDB; 

CREATE TABLE ENTREPRISE( 
	ent_id INT NOT NULL auto_increment, 
	entr_siret VARCHAR(14) NOT NULL, 
	ent_raisonsociale VARCHAR(65) NOT NULL, 
	ent_adresse1 VARCHAR(45) NOT NULL, 
	ent_adresse2 VARCHAR(45), 
	ent_CP VARCHAR(5) NOT NULL, 
	ent_ville VARCHAR(45) NOT NULL, 
	ent_telephone VARCHAR(10) NOT NULL, 
	ent_fax VARCHAR(10), 
	ent_mail VARCHAR(45),
	ent_login INT NOT NULL,
	CONSTRAINT PK_ENTREPRISE PRIMARY KEY (ent_id),
	CONSTRAINT FK_ENT_LOG FOREIGN KEY (ent_login) REFERENCES LOGIN(log_id)
)Engine=InnoDB;

CREATE TABLE FONCTION(
	fct_id INT NOT NULL auto_increment,
	fct_code VARCHAR(5) NOT NULL,
	fct_libelle VARCHAR(35) NOT NULL,
	CONSTRAINT PK_FCT PRIMARY KEY (fct_id)
)Engine=InnoDB;

CREATE TABLE EMPLOYE(
	emp_id INT NOT NULL auto_increment,
	emp_nom VARCHAR(45) NOT NULL,
	emp_prenom VARCHAR(45) NOT NULL,
	emp_adresse1 VARCHAR(45) NOT NULL,
	emp_adresse2 VARCHAR(45) NOT NULL,
	emp_CP VARCHAR(5) NOT NULL,
	emp_ville VARCHAR(45) NOT NULL,
	emp_telephone VARCHAR(10) NOT NULL,
	emp_mail VARCHAR(45) NOT NULL,
	emp_fonction INT NOT NULL,
	emp_login INT NOT NULL,
	CONSTRAINT PK_EMP PRIMARY KEY (emp_id),
	CONSTRAINT FK_FCTEMP FOREIGN KEY (emp_fonction) REFERENCES FONCTION(fct_id),
	CONSTRAINT FK_LOG_EMP FOREIGN KEY (emp_login) REFERENCES LOGIN(log_id) 
)Engine=InnoDB;

CREATE TABLE METIER(
	met_id INT NOT NULL auto_increment,
	met_code VARCHAR(15) NOT NULL,
	met_libelle VARCHAR(45) NOT NULL,
	CONSTRAINT PK_METIER PRIMARY KEY (met_id)
)Engine=InnoDB;

CREATE TABLE EXPERIENCE(
	exp_id INT NOT NULL,
	exp_code VARCHAR(2) NOT NULL,
	exp_libelle VARCHAR(25) NOT NULL,
	CONSTRAINT PK_EXP PRIMARY KEY (exp_id)
)Engine=InnoDB;

CREATE TABLE DIPLOME(
	dip_id INT NOT NULL,
	dip_code VARCHAR(10) NOT NULL,
	dip_libelle VARCHAR(45) NOT NULL,
	CONSTRAINT PK_DIPLOME PRIMARY KEY (dip_id)
)Engine=InnoDB;


CREATE TABLE MOTIF_DE_RECOURS(
	mot_id INT NOT NULL auto_increment,
	mot_code VARCHAR(15) NOT NULL,
	mot_libelle VARCHAR(45) NOT NULL,
	CONSTRAINT PK_MOTIF PRIMARY KEY (mot_id)
)Engine=InnoDB;

CREATE TABLE TYPE_OFFRE(
	type_id INT NOT NULL auto_increment,
	type_code VARCHAR(3) NOT NULL,
	type_libelle VARCHAR(45) NOT NULL,
	CONSTRAINT PK_TYPEOFFRE PRIMARY KEY (type_id)
)Engine=InnoDB;

CREATE TABLE OFFRE(
	off_numero INT NOT NULL auto_increment,
	off_libelle VARCHAR(95) NOT NULL,
	off_dateDebutPrevisionnel DATE NOT NULL,
	off_dateFinPrevisionnel DATE,
	off_periodeEssaiJours INT NOT NULL,
	off_nombrePersonnes INT NOT NULL,
	off_motif INT NOT NULL,
	off_type INT NOT NULL,
	off_employe INT NOT NULL,
	off_entreprise INT NOT NULL,
	off_metier INT NOT NULL,
	CONSTRAINT PK_OFFRE PRIMARY KEY (off_numero),
	CONSTRAINT FK_MOTIF_OFFRE FOREIGN KEY (off_motif) REFERENCES MOTIF_DE_RECOURS(mot_id),
	CONSTRAINT FK_TYPE_OFFRE FOREIGN KEY (off_type) REFERENCES TYPE_OFFRE(type_id),
	CONSTRAINT FK_EMPLOYE_OFFRE FOREIGN KEY (off_employe) REFERENCES EMPLOYE(emp_id),
	CONSTRAINT FK_ENTREPRISE_OFFRE FOREIGN KEY (off_entreprise) REFERENCES ENTREPRISE(ent_id),
	CONSTRAINT FK_METIER_OFFRE FOREIGN KEY (off_metier) REFERENCES METIER(met_id)
)Engine=InnoDB;

CREATE TABLE INTERIMAIRE(
	int_id INT NOT NULL auto_increment,
	int_ss VARCHAR(15) NOT NULL,
	int_nom VARCHAR(45) NOT NULL,
	int_prenom VARCHAR(45) NOT NULL,
	int_adr1 VARCHAR(45) NOT NULL,
	int_adr2 VARCHAR(45),
	int_cp VARCHAR(5) NOT NULL,
	int_ville VARCHAR(45) NOT NULL,
	int_telephone VARCHAR(10) NOT NULL,
	int_mobile VARCHAR(10),
	int_mail VARCHAR(45) NOT NULL,
	int_metier INT NOT NULL,
	int_civilite INT NOT NULL,
	int_login INT NOT NULL,
	CONSTRAINT PK_SS PRIMARY KEY (int_id),
	CONSTRAINT FK_INTERMETIER FOREIGN KEY (int_metier) REFERENCES METIER(met_id),
	CONSTRAINT FK_CIV_INTERIMAIRE FOREIGN KEY (int_civilite) REFERENCES CIVILITES(civ_id),
	CONSTRAINT FK_LOG_INT FOREIGN KEY (int_login) REFERENCES LOGIN(log_id)
)Engine=InnoDB;

CREATE TABLE QUALIFICATION(
	qual_metier INT NOT NULL,
	qual_experience INT NOT NULL,
	qual_diplome INT NOT NULL,
	qual_interimaire INT NOT NULL,
	qual_offre INT NOT NULL,
	CONSTRAINT FK_QUAL_METIER FOREIGN KEY (qual_metier) REFERENCES METIER(met_id),
	CONSTRAINT FK_QUAL_EXP FOREIGN KEY (qual_experience) REFERENCES EXPERIENCE(exp_id),
	CONSTRAINT FK_QUAL_DIPLOME FOREIGN KEY (qual_diplome) REFERENCES DIPLOME(dip_id),
	CONSTRAINT FK_QUAL_INT FOREIGN KEY (qual_interimaire) REFERENCES INTERIMAIRE(int_id),
	CONSTRAINT FK_QUAL_OFF FOREIGN KEY (qual_offre) REFERENCES OFFRE(off_numero)
)Engine=InnoDB;

CREATE TABLE DOCUMENTS(
	doc_id INT NOT NULL auto_increment,
	doc_code VARCHAR(5) NOT NULL,
	doc_libelle VARCHAR(65) NOT NULL,
	CONSTRAINT PK_CODE PRIMARY KEY (doc_id)
)Engine=InnoDB;

CREATE TABLE DOSSIER(
	dos_id INT NOT NULL auto_increment,
	dos_date DATE NOT NULL,
	dos_chemin VARCHAR(95) NOT NULL,
	dos_interimaire INT NOT NULL,
	dos_document INT NOT NULL,
	CONSTRAINT PK_DOSSIER PRIMARY KEY (dos_id),
	CONSTRAINT FK_DOS_INT FOREIGN KEY (dos_interimaire) REFERENCES INTERIMAIRE(int_id),
	CONSTRAINT FK_DOS_DOC FOREIGN KEY (dos_document) REFERENCES DOCUMENTS(doc_id)
)Engine=InnoDB;

CREATE TABLE CONTRAT_DE_MISSION(
	cdm_id INT NOT NULL auto_increment,
	cdm_date DATE NOT NULL,
	cdm_dateDebut DATE NOT NULL,
	cdm_dossier INT NOT NULL,
	cdm_offre INT NOT NULL,
	CONSTRAINT PK_CDM PRIMARY KEY (cdm_id),
	CONSTRAINT FK_CDM_DOS FOREIGN KEY (cdm_dossier) REFERENCES DOSSIER(dos_id),
	CONSTRAINT FK_CDM_OFFRE FOREIGN KEY (cdm_offre) REFERENCES OFFRE(off_numero)
)Engine=InnoDB;

CREATE TABLE CDI(
	cdi_id INT NOT NULL,
	CONSTRAINT FK_CDI_CDM FOREIGN KEY (cdi_id) REFERENCES CONTRAT_DE_MISSION(cdm_id)
)Engine=InnoDB;

CREATE TABLE CDD(
	cdd_id INT NOT NULL,
	cdd_type VARCHAR(25) NOT NULL,
	cdd_dureeMois INT NOT NULL, 
	CONSTRAINT FK_CDD_CDM FOREIGN KEY (cdd_id) REFERENCES CONTRAT_DE_MISSION(cdm_id)
)Engine=InnoDB;
